// Felddefinitionen für das Registrierungsformular – einfach erweiterbar
import type { FieldDefinition } from "@/components/form/FormField"

export const signupFields: FieldDefinition[] = [
	{
		id: 'firstname',
		label: 'Vorname',
		required: true,
		autoComplete: 'given-name',
		group: "personal",
	},
	{
		id: 'lastname',
		label: 'Nachname',
		required: true,
		autoComplete: 'family-name',
		group: "personal",
	},
	{
		id: 'password',
		label: 'Passwort',
		type: 'password',
		required: true,
		minLength: 8,
		autoComplete: 'new-password',
		group: "personal",
	},
	{
		id: 'passwordConfirm',
		label: 'Passwort wiederholen',
		type: 'password',
		required: true,
		minLength: 8,
		autoComplete: 'new-password',
		group: "personal",
	},
	{
		id: 'email',
		label: 'E-Mail',
		type: 'email',
		required: true,
		autoComplete: 'email',
		group: "personal",
	},
	{
		id: 'phone',
		label: 'Telefon',
		type: 'tel',
		required: true,
		autoComplete: 'tel',
		group: "personal",
	},
	{
		id: 'companyName',
		label: 'Firmenname',
		required: true,
		autoComplete: 'organization',
		group: "company",
	},
	{
		id: 'companyContactFirstname',
		label: 'Vorname Ansprechpartner',
		required: true,
		autoComplete: 'given-name',
		group: "company",
	},
	{
		id: 'companyContactLastname',
		label: 'Nachname Ansprechpartner',
		required: true,
		autoComplete: 'family-name',
		group: "company",
	},
	{
		id: 'companyAddress',
		label: 'Straße und Hausnummer der Niederlassung',
		required: true,
		autoComplete: 'street-address',
		group: "company",
	},
	{
		id: 'companyPostcode',
		label: 'PLZ der Niederlassung',
		pattern: "[0-9]{5}",
		maxLength: 5,
		minLength: 5,
		inputMode: "numeric",
		description: "Bitte 5 Ziffern eingeben",
		required: true,
		autoComplete: 'postal-code',
		group: "company",
	},
	{
		id: 'companyCity',
		label: 'Ort der Niederlassung',
		required: true,
		autoComplete: 'address-level2',
		group: "company",
	},
	{
		id: 'companyPhone',
		label: 'Telefon der Firma',
		type: 'tel',
		required: true,
		group: "company",
	},
	{
		id: 'companyEmail',
		label: 'E-Mail der Firma',
		type: 'email',
		required: true,
		group: "company",
	},
]
